"""Added new column to Visitor

Revision ID: 75181e8fc974
Revises: 1b3d77e69d88
Create Date: 2024-08-13 18:35:03.131837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75181e8fc974'
down_revision = '1b3d77e69d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###
