"""empty message

Revision ID: 7e99e785b893
Revises: c5cb8e04c265
Create Date: 2024-08-05 17:28:43.206081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e99e785b893'
down_revision = 'c5cb8e04c265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_section')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='about_section_pkey')
    )
    # ### end Alembic commands ###
