"""Initial migration.

Revision ID: c5cb8e04c265
Revises: 
Create Date: 2024-08-02 21:46:34.804236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5cb8e04c265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blog_Data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('author', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('Blog_Data_email_key', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('subject')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Blog_Data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('Blog_Data_email_key', ['email'])
        batch_op.drop_column('date_created')
        batch_op.drop_column('author')
        batch_op.drop_column('content')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
